# Site settings
title: Kwan Lab
header-img: img/fetal-bg.jpg
description: "The Kwan laboratory at the University of Michigan for the study of cerebral cortical development, evolution, and dysfunction."
baseurl: ""
url: "http://kwanlab.org"
twitter_username: kwanlab
github_username:  thekwanlab

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","*.json","README.md","Gemfile","*.lock"]
